const DatasPlanets = [
  {
    id: 1,
    name: "Captação de recursos",
    imageUrl: "/images/satelites/recursos.png",
    style: "CaptacaoRecursos",
    size: 52,
  },
  {
    id: 2,
    name: "Finanças",
    imageUrl: "/images/satelites/financas.png",
    style: "Financas",
    size: 52,
  },
  {
    id: 3,
    name: "Jurídico",
    imageUrl: "/images/satelites/juridico.png",
    style: "Juridico",
    size: 52,
  },
  {
    id: 4,
    name: "Gestão de Pessoas",
    imageUrl: "/images/satelites/pessoas.png",
    style: "GestaoPessoas",
    size: 52,
  },
  {
    id: 5,
    name: "Marketing",
    imageUrl: "/images/satelites/marketing.png",
    style: "Marketing",
    size: 52,
  },
  {
    id: 6,
    name: "Instituto Dorina Nowill",
    imageUrl: "/images/satelites/instituto.png",
    style: "Intituto",
    size: 200,
  },
  {
    id: 7,
    name: "Avaliação de Impacto",
    imageUrl: "/images/satelites/impacto.png",
    style: "AvaliacaoImpacto",
    size: 52,
  },
  {
    id: 8,
    name: "Gestão de Projetos",
    imageUrl: "/images/satelites/projetos.png",
    style: "GestaoProjetos",
    size: 52,
  },
  {
    id: 9,
    name: "Sustentabilidade",
    imageUrl: "/images/satelites/sustentabilidade.png",
    style: "Sustentabilidade",
    size: 52,
  },
  {
    id: 10,
    name: "Estratégia",
    imageUrl: "/images/satelites/estrategia.png",
    style: "Estrategia",
    size: 52,
  },
  {
    id: 11,
    name: "Liderança",
    imageUrl: "/images/satelites/lideranca.png",
    style: "Lideranca",
    size: 52,
  },
];

export default DatasPlanets;
