export const DatasPlanets = [
  {
    id: 1,
    name: "Captação de recursos",
    style: "col-start-1 col-end-2 row-start-1 row-end-3",
    imageUrl: "/images/satelites/recursos.png",
    width: 52,
    height: 52,
  },
  {
    id: 2,
    name: "Finanças",
    style: "col-start-3 col-end-3 row-start-1 row-end-1",
    imageUrl: "/images/satelites/financas.png",
    width: 40,
    height: 40,
  },
  {
    id: 3,
    name: "Jurídico",
    style: "col-start-6 col-end-7 row-start-1 row-end-1",
    imageUrl: "/images/satelites/juridico.png",
    width: 55,
    height: 55,
  },
  {
    id: 4,
    name: "Gestão de Pessoas",
    style: "col-start-8 col-end-9 row-start-1 row-end-3",
    imageUrl: "/images/satelites/pessoas.png",
    width: 55,
    height: 55,
  },
  {
    id: 4,
    name: "Marketing",
    style: "col-start-2 col-end-2 row-start-3 row-end-3",
    imageUrl: "/images/satelites/marketing.png",
    width: 38,
    height: 38,
  },
  {
    id: 5,
    name: "Instituto Dorina Nowill",
    style: "col-start-4 col-end-6 row-start-2 row-end-5",
    imageUrl: "/images/satelites/instituto.png",
    width: 200,
    height: 150,
  },
  {
    id: 6,
    name: "Avaliação de Impacto",
    style: "col-start-7 col-end-8 row-start-3 row-end-4",
    imageUrl: "/images/satelites/impacto.png",
    width: 64,
    height: 64,
  },
  {
    id: 7,
    name: "Gestão de Projetos",
    style: "col-start-1 col-end-1 row-start-4 row-end-6",
    imageUrl: "/images/satelites/projetos.png",
    width: 40,
    height: 40,
  },
  {
    id: 7,
    name: "Sustentabilidade",
    style: "col-start-3 col-end-4 row-start-5 row-end-7",
    imageUrl: "/images/satelites/sustentabilidade.png",
    width: 55,
    height: 55,
  },
  {
    id: 8,
    name: "Estratégia",
    style: "col-start-6 col-end-6 row-start-5 row-end-7",
    imageUrl: "/images/satelites/estrategia.png",
    width: 55,
    height: 55,
  },
  {
    id: 9,
    name: "Liderança",
    style: "col-start-8 col-end-9 row-start-4 row-end-6",
    imageUrl: "/images/satelites/lideranca.png",
    width: 50,
    height: 50,
  },
];
